import React from "react";
import ReactDOM from "react-dom";
import List from "../list";
import { render, cleanup } from "@testing-library/react";

describe("List Component", () => {
  let list = null;
  beforeEach(() => {
    list = [
      {
        list: {
          id: "5ffa88cb8c4e9e07ec1ed74d",
          name: "To Do",
          closed: false,
          pos: 16384,
          softLimit: null,
          idBoard: "5ffa88cb8c4e9e07ec1ed74c",
          subscribed: false,
        },
        cards: [
          {
            id: "5ffb10d68a5268435ca4b9a4",
            checkItemStates: null,
            closed: false,
            dateLastActivity: "2021-01-11T06:18:26.954Z",
            desc: "",
            descData: null,
            dueReminder: null,
            idBoard: "5ffa88cb8c4e9e07ec1ed74c",
            idList: "5ffa88cb8c4e9e07ec1ed74d",
            idMembersVoted: [],
            idShort: 23,
            idAttachmentCover: null,
            idLabels: [],
            manualCoverAttachment: false,
            name: "With a backend of your choice",
            pos: 32768,
            shortLink: "zhSpIs48",
            isTemplate: false,
            cardRole: null,
            badges: {
              attachmentsByType: { trello: { board: 0, card: 0 } },
              location: false,
              votes: 0,
              viewingMemberVoted: false,
              subscribed: false,
              fogbugz: "",
              checkItems: 0,
              checkItemsChecked: 0,
              checkItemsEarliestDue: null,
              comments: 0,
              attachments: 0,
              description: false,
              due: null,
              dueComplete: false,
              start: null,
            },
            dueComplete: false,
            due: null,
            idChecklists: [],
            idMembers: [],
            labels: [],
            shortUrl: "https://trello.com/c/zhSpIs48",
            start: null,
            subscribed: false,
            url:
              "https://trello.com/c/zhSpIs48/23-with-a-backend-of-your-choice",
            cover: {
              idAttachment: null,
              color: null,
              idUploadedBackground: null,
              size: "normal",
              brightness: "light",
            },
          },
          {
            id: "5ffa88db78b8b0328c60475a",
            checkItemStates: null,
            closed: false,
            dateLastActivity: "2021-01-10T17:53:47.603Z",
            desc: "",
            descData: null,
            dueReminder: null,
            idBoard: "5ffa88cb8c4e9e07ec1ed74c",
            idList: "5ffa88cb8c4e9e07ec1ed74d",
            idMembersVoted: [],
            idShort: 1,
            idAttachmentCover: null,
            idLabels: [],
            manualCoverAttachment: false,
            name: "Create a backend api",
            pos: 196607,
            shortLink: "3aouVtCd",
            isTemplate: false,
            cardRole: null,
            badges: {
              attachmentsByType: { trello: { board: 0, card: 0 } },
              location: false,
              votes: 0,
              viewingMemberVoted: false,
              subscribed: false,
              fogbugz: "",
              checkItems: 0,
              checkItemsChecked: 0,
              checkItemsEarliestDue: null,
              comments: 0,
              attachments: 0,
              description: false,
              due: null,
              dueComplete: false,
              start: null,
            },
            dueComplete: false,
            due: null,
            idChecklists: [],
            idMembers: [],
            labels: [],
            shortUrl: "https://trello.com/c/3aouVtCd",
            start: null,
            subscribed: false,
            url: "https://trello.com/c/3aouVtCd/1-create-a-backend-api",
            cover: {
              idAttachment: null,
              color: null,
              idUploadedBackground: null,
              size: "normal",
              brightness: "light",
            },
          },
          {
            id: "5ffb404d2415b07da5e73039",
            checkItemStates: null,
            closed: false,
            dateLastActivity: "2021-01-10T17:58:37.984Z",
            desc: "",
            descData: null,
            dueReminder: null,
            idBoard: "5ffa88cb8c4e9e07ec1ed74c",
            idList: "5ffa88cb8c4e9e07ec1ed74d",
            idMembersVoted: [],
            idShort: 27,
            idAttachmentCover: null,
            idLabels: [],
            manualCoverAttachment: false,
            name: "Late night work",
            pos: 212991,
            shortLink: "lOZjhgoG",
            isTemplate: false,
            cardRole: null,
            badges: {
              attachmentsByType: { trello: { board: 0, card: 0 } },
              location: false,
              votes: 0,
              viewingMemberVoted: false,
              subscribed: false,
              fogbugz: "",
              checkItems: 0,
              checkItemsChecked: 0,
              checkItemsEarliestDue: null,
              comments: 0,
              attachments: 0,
              description: false,
              due: null,
              dueComplete: false,
              start: null,
            },
            dueComplete: false,
            due: null,
            idChecklists: [],
            idMembers: [],
            labels: [],
            shortUrl: "https://trello.com/c/lOZjhgoG",
            start: null,
            subscribed: false,
            url: "https://trello.com/c/lOZjhgoG/27-late-night-work",
            cover: {
              idAttachment: null,
              color: null,
              idUploadedBackground: null,
              size: "normal",
              brightness: "light",
            },
          },
        ],
      },
      {
        list: {
          id: "5ffa88cb8c4e9e07ec1ed74f",
          name: "Done",
          closed: false,
          pos: 49152,
          softLimit: null,
          idBoard: "5ffa88cb8c4e9e07ec1ed74c",
          subscribed: false,
        },
        cards: [
          {
            id: "5ffb10c9c4a9d4801b96ab46",
            checkItemStates: null,
            closed: false,
            dateLastActivity: "2021-01-11T05:19:17.659Z",
            desc: "",
            descData: null,
            dueReminder: null,
            idBoard: "5ffa88cb8c4e9e07ec1ed74c",
            idList: "5ffa88cb8c4e9e07ec1ed74f",
            idMembersVoted: [],
            idShort: 22,
            idAttachmentCover: null,
            idLabels: [],
            manualCoverAttachment: false,
            name: "Create a React application",
            pos: 16384,
            shortLink: "w5Pdld7p",
            isTemplate: false,
            cardRole: null,
            badges: {
              attachmentsByType: { trello: { board: 0, card: 0 } },
              location: false,
              votes: 0,
              viewingMemberVoted: false,
              subscribed: false,
              fogbugz: "",
              checkItems: 0,
              checkItemsChecked: 0,
              checkItemsEarliestDue: null,
              comments: 0,
              attachments: 0,
              description: false,
              due: null,
              dueComplete: false,
              start: null,
            },
            dueComplete: false,
            due: null,
            idChecklists: [],
            idMembers: [],
            labels: [],
            shortUrl: "https://trello.com/c/w5Pdld7p",
            start: null,
            subscribed: false,
            url: "https://trello.com/c/w5Pdld7p/22-create-a-react-application",
            cover: {
              idAttachment: null,
              color: null,
              idUploadedBackground: null,
              size: "normal",
              brightness: "light",
            },
          },
          {
            id: "5ffb10ebc6ba3043aa82de67",
            checkItemStates: null,
            closed: false,
            dateLastActivity: "2021-01-11T04:47:24.865Z",
            desc: "",
            descData: null,
            dueReminder: null,
            idBoard: "5ffa88cb8c4e9e07ec1ed74c",
            idList: "5ffa88cb8c4e9e07ec1ed74f",
            idMembersVoted: [],
            idShort: 24,
            idAttachmentCover: null,
            idLabels: [],
            manualCoverAttachment: false,
            name: "Access trello API through the backend",
            pos: 49152,
            shortLink: "eSQdKXjK",
            isTemplate: false,
            cardRole: null,
            badges: {
              attachmentsByType: { trello: { board: 0, card: 0 } },
              location: false,
              votes: 0,
              viewingMemberVoted: false,
              subscribed: false,
              fogbugz: "",
              checkItems: 0,
              checkItemsChecked: 0,
              checkItemsEarliestDue: null,
              comments: 0,
              attachments: 0,
              description: false,
              due: null,
              dueComplete: false,
              start: null,
            },
            dueComplete: false,
            due: null,
            idChecklists: [],
            idMembers: [],
            labels: [],
            shortUrl: "https://trello.com/c/eSQdKXjK",
            start: null,
            subscribed: false,
            url:
              "https://trello.com/c/eSQdKXjK/24-access-trello-api-through-the-backend",
            cover: {
              idAttachment: null,
              color: null,
              idUploadedBackground: null,
              size: "normal",
              brightness: "light",
            },
          },
          {
            id: "5ffb1107acd71e0cb6b502e7",
            checkItemStates: null,
            closed: false,
            dateLastActivity: "2021-01-10T17:54:04.391Z",
            desc: "",
            descData: null,
            dueReminder: null,
            idBoard: "5ffa88cb8c4e9e07ec1ed74c",
            idList: "5ffa88cb8c4e9e07ec1ed74f",
            idMembersVoted: [],
            idShort: 25,
            idAttachmentCover: null,
            idLabels: [],
            manualCoverAttachment: false,
            name: "The application should render the lists",
            pos: 65536,
            shortLink: "rgIyDZGG",
            isTemplate: false,
            cardRole: null,
            badges: {
              attachmentsByType: { trello: { board: 0, card: 0 } },
              location: false,
              votes: 0,
              viewingMemberVoted: false,
              subscribed: false,
              fogbugz: "",
              checkItems: 0,
              checkItemsChecked: 0,
              checkItemsEarliestDue: null,
              comments: 0,
              attachments: 0,
              description: false,
              due: null,
              dueComplete: false,
              start: null,
            },
            dueComplete: false,
            due: null,
            idChecklists: [],
            idMembers: [],
            labels: [],
            shortUrl: "https://trello.com/c/rgIyDZGG",
            start: null,
            subscribed: false,
            url:
              "https://trello.com/c/rgIyDZGG/25-the-application-should-render-the-lists",
            cover: {
              idAttachment: null,
              color: null,
              idUploadedBackground: null,
              size: "normal",
              brightness: "light",
            },
          },
        ],
      },
    ];
  });
  afterEach(cleanup);

  it("renders without crashing", () => {
    const div = document.createElement("div");
    list.forEach((listItem, i) => {
      ReactDOM.render(<List list={listItem} />, div);
    });
  });
  it("should render the header with correct text", () => {
    const getList = jest.fn();
    list.forEach((listItem, i) => {
      const { container } = render(
        <List
          list={listItem}
          key={i}
          data-id={listItem.list.id}
          updateLists={getList}
          changeId={
            listItem.list.name === "Done" ? list[0].list.id : list[1].list.id
          }
        />
      );
      expect(container.querySelector("h2")).toHaveTextContent(
        listItem.list.name
      );
    });
  });
});
